FROM maven:3.9.11-eclipse-temurin-21 as build

WORKDIR /app

COPY . .

RUN mvn clean package

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/ .

EXPOSE 8080

CMD ["java","-jar","spring-boot-web.jar"]